import type { WcagSuccessCriterion } from '@a11y/shared-types';

// WCAG 2.2 Level A + AA. Source: https://www.w3.org/TR/WCAG22/
// Includes the 9 new SCs added in 2.2 (2.4.11, 2.4.12, 2.4.13, 2.5.7, 2.5.8, 3.2.6, 3.3.7, 3.3.8, 3.3.9).
export const CRITERIA: ReadonlyArray<WcagSuccessCriterion> = [
  // 1. Perceivable
  {
    sc: '1.1.1',
    level: 'A',
    version: '2.0',
    title: 'Non-text Content',
    description: 'All non-text content has a text alternative.',
  },
  {
    sc: '1.2.1',
    level: 'A',
    version: '2.0',
    title: 'Audio-only and Video-only (Prerecorded)',
    description: 'Provide alternative for time-based media.',
  },
  {
    sc: '1.2.2',
    level: 'A',
    version: '2.0',
    title: 'Captions (Prerecorded)',
    description: 'Captions for prerecorded audio in synced media.',
  },
  {
    sc: '1.2.3',
    level: 'A',
    version: '2.0',
    title: 'Audio Description or Media Alternative (Prerecorded)',
    description: 'Audio description for prerecorded video.',
  },
  {
    sc: '1.2.4',
    level: 'AA',
    version: '2.0',
    title: 'Captions (Live)',
    description: 'Captions for live synced media.',
  },
  {
    sc: '1.2.5',
    level: 'AA',
    version: '2.0',
    title: 'Audio Description (Prerecorded)',
    description: 'Audio description for prerecorded synced media.',
  },
  {
    sc: '1.3.1',
    level: 'A',
    version: '2.0',
    title: 'Info and Relationships',
    description: 'Structure conveyed visually is also programmatic.',
  },
  {
    sc: '1.3.2',
    level: 'A',
    version: '2.0',
    title: 'Meaningful Sequence',
    description: 'Reading order is correct in the DOM.',
  },
  {
    sc: '1.3.3',
    level: 'A',
    version: '2.0',
    title: 'Sensory Characteristics',
    description: "Instructions don't rely on sensory cues alone.",
  },
  {
    sc: '1.3.4',
    level: 'AA',
    version: '2.1',
    title: 'Orientation',
    description: 'Content not restricted to portrait or landscape.',
  },
  {
    sc: '1.3.5',
    level: 'AA',
    version: '2.1',
    title: 'Identify Input Purpose',
    description: 'Inputs collecting user info have appropriate autocomplete.',
  },
  {
    sc: '1.4.1',
    level: 'A',
    version: '2.0',
    title: 'Use of Color',
    description: 'Color is not the only way to convey information.',
  },
  {
    sc: '1.4.2',
    level: 'A',
    version: '2.0',
    title: 'Audio Control',
    description: 'Auto-playing audio can be paused.',
  },
  {
    sc: '1.4.3',
    level: 'AA',
    version: '2.0',
    title: 'Contrast (Minimum)',
    description: 'Text has contrast ratio of at least 4.5:1.',
  },
  {
    sc: '1.4.4',
    level: 'AA',
    version: '2.0',
    title: 'Resize Text',
    description: 'Text can be resized up to 200% without loss of content.',
  },
  {
    sc: '1.4.5',
    level: 'AA',
    version: '2.0',
    title: 'Images of Text',
    description: 'Text is preferred over images of text.',
  },
  {
    sc: '1.4.10',
    level: 'AA',
    version: '2.1',
    title: 'Reflow',
    description: 'Content reflows at 320 CSS px width without 2D scrolling.',
  },
  {
    sc: '1.4.11',
    level: 'AA',
    version: '2.1',
    title: 'Non-text Contrast',
    description: 'UI components have 3:1 contrast against adjacent colors.',
  },
  {
    sc: '1.4.12',
    level: 'AA',
    version: '2.1',
    title: 'Text Spacing',
    description: 'No content loss when text spacing is adjusted.',
  },
  {
    sc: '1.4.13',
    level: 'AA',
    version: '2.1',
    title: 'Content on Hover or Focus',
    description: 'Hover/focus content can be dismissed, hovered, persistent.',
  },

  // 2. Operable
  {
    sc: '2.1.1',
    level: 'A',
    version: '2.0',
    title: 'Keyboard',
    description: 'All functionality is available from a keyboard.',
  },
  {
    sc: '2.1.2',
    level: 'A',
    version: '2.0',
    title: 'No Keyboard Trap',
    description: 'Keyboard focus can be moved away from any component.',
  },
  {
    sc: '2.1.4',
    level: 'A',
    version: '2.1',
    title: 'Character Key Shortcuts',
    description: 'Single-character shortcuts can be turned off or remapped.',
  },
  {
    sc: '2.2.1',
    level: 'A',
    version: '2.0',
    title: 'Timing Adjustable',
    description: 'Time limits can be turned off, adjusted, or extended.',
  },
  {
    sc: '2.2.2',
    level: 'A',
    version: '2.0',
    title: 'Pause, Stop, Hide',
    description: 'Moving content can be paused, stopped, or hidden.',
  },
  {
    sc: '2.3.1',
    level: 'A',
    version: '2.0',
    title: 'Three Flashes or Below Threshold',
    description: 'Content does not flash more than 3 times per second.',
  },
  {
    sc: '2.4.1',
    level: 'A',
    version: '2.0',
    title: 'Bypass Blocks',
    description: 'Skip-to-content mechanism is provided.',
  },
  {
    sc: '2.4.2',
    level: 'A',
    version: '2.0',
    title: 'Page Titled',
    description: 'Pages have descriptive titles.',
  },
  {
    sc: '2.4.3',
    level: 'A',
    version: '2.0',
    title: 'Focus Order',
    description: 'Focusable components receive focus in a logical order.',
  },
  {
    sc: '2.4.4',
    level: 'A',
    version: '2.0',
    title: 'Link Purpose (In Context)',
    description: 'Link purpose can be determined from the link text.',
  },
  {
    sc: '2.4.5',
    level: 'AA',
    version: '2.0',
    title: 'Multiple Ways',
    description: 'Multiple ways to locate a page within a set.',
  },
  {
    sc: '2.4.6',
    level: 'AA',
    version: '2.0',
    title: 'Headings and Labels',
    description: 'Headings and labels describe topic or purpose.',
  },
  {
    sc: '2.4.7',
    level: 'AA',
    version: '2.0',
    title: 'Focus Visible',
    description: 'Keyboard focus indicator is visible.',
  },
  {
    sc: '2.4.11',
    level: 'AA',
    version: '2.2',
    title: 'Focus Not Obscured (Minimum)',
    description: 'Focused element is not entirely hidden by author content.',
  },
  {
    sc: '2.4.12',
    level: 'AAA',
    version: '2.2',
    title: 'Focus Not Obscured (Enhanced)',
    description: 'Focused element is not hidden at all by author content.',
  },
  {
    sc: '2.4.13',
    level: 'AAA',
    version: '2.2',
    title: 'Focus Appearance',
    description: 'Focus indicator meets size and contrast requirements.',
  },
  {
    sc: '2.5.1',
    level: 'A',
    version: '2.1',
    title: 'Pointer Gestures',
    description: 'Multi-point or path-based gestures have alternatives.',
  },
  {
    sc: '2.5.2',
    level: 'A',
    version: '2.1',
    title: 'Pointer Cancellation',
    description: 'Pointer-down events can be aborted or undone.',
  },
  {
    sc: '2.5.3',
    level: 'A',
    version: '2.1',
    title: 'Label in Name',
    description: 'Accessible name contains visible label text.',
  },
  {
    sc: '2.5.4',
    level: 'A',
    version: '2.1',
    title: 'Motion Actuation',
    description: 'Motion-triggered actions have UI alternatives.',
  },
  {
    sc: '2.5.7',
    level: 'AA',
    version: '2.2',
    title: 'Dragging Movements',
    description: 'Drag interactions have a single-pointer alternative.',
  },
  {
    sc: '2.5.8',
    level: 'AA',
    version: '2.2',
    title: 'Target Size (Minimum)',
    description: 'Pointer targets are at least 24x24 CSS px (with exceptions).',
  },

  // 3. Understandable
  {
    sc: '3.1.1',
    level: 'A',
    version: '2.0',
    title: 'Language of Page',
    description: 'Default language is programmatically determined.',
  },
  {
    sc: '3.1.2',
    level: 'AA',
    version: '2.0',
    title: 'Language of Parts',
    description: 'Language of each passage is programmatically determined.',
  },
  {
    sc: '3.2.1',
    level: 'A',
    version: '2.0',
    title: 'On Focus',
    description: 'Receiving focus does not initiate a context change.',
  },
  {
    sc: '3.2.2',
    level: 'A',
    version: '2.0',
    title: 'On Input',
    description: 'Changing a setting does not auto-trigger context change.',
  },
  {
    sc: '3.2.3',
    level: 'AA',
    version: '2.0',
    title: 'Consistent Navigation',
    description: 'Navigation is in the same relative order across pages.',
  },
  {
    sc: '3.2.4',
    level: 'AA',
    version: '2.0',
    title: 'Consistent Identification',
    description: 'Components with the same function are identified consistently.',
  },
  {
    sc: '3.2.6',
    level: 'A',
    version: '2.2',
    title: 'Consistent Help',
    description: 'Help mechanism is in the same relative order across pages.',
  },
  {
    sc: '3.3.1',
    level: 'A',
    version: '2.0',
    title: 'Error Identification',
    description: 'Input errors are identified and described to users.',
  },
  {
    sc: '3.3.2',
    level: 'A',
    version: '2.0',
    title: 'Labels or Instructions',
    description: 'Labels or instructions are provided when input is required.',
  },
  {
    sc: '3.3.3',
    level: 'AA',
    version: '2.0',
    title: 'Error Suggestion',
    description: 'Suggestions are provided for input errors when known.',
  },
  {
    sc: '3.3.4',
    level: 'AA',
    version: '2.0',
    title: 'Error Prevention (Legal, Financial, Data)',
    description: 'Submissions are reversible, checked, or confirmed.',
  },
  {
    sc: '3.3.7',
    level: 'A',
    version: '2.2',
    title: 'Redundant Entry',
    description: 'Information previously entered is auto-populated or available.',
  },
  {
    sc: '3.3.8',
    level: 'AA',
    version: '2.2',
    title: 'Accessible Authentication (Minimum)',
    description: 'No cognitive function test required for auth, with exceptions.',
  },

  // 4. Robust
  {
    sc: '4.1.1',
    level: 'A',
    version: '2.0',
    title: 'Parsing (deprecated in 2.2)',
    description: 'Markup is well-formed (obsolete in WCAG 2.2).',
  },
  {
    sc: '4.1.2',
    level: 'A',
    version: '2.0',
    title: 'Name, Role, Value',
    description: 'Custom controls expose name, role, value programmatically.',
  },
  {
    sc: '4.1.3',
    level: 'AA',
    version: '2.1',
    title: 'Status Messages',
    description: 'Status messages are programmatically determinable.',
  },
];

const BY_SC = new Map(CRITERIA.map((c) => [c.sc, c]));

export function lookupCriterion(sc: string): WcagSuccessCriterion | undefined {
  return BY_SC.get(sc);
}
